### PR TITLE
Add a .gitignore file

### PR DESCRIPTION
**Pull request by theblobscp**

### CODE REVIEW

**Comment by Dust-trust** [comment]
Just a .gitignore file

**Comment by wa7sa34cx** [comment]
> Just a .gitignore file

For what purpose? This repository doesn't have any git initialization 🤷‍♂️

**Comment by theblobscp** [comment]
Why not have one

**Comment by mauro-balades** [comment]
omfg

**Comment by aloisdg** [comment]
> Why not have one

because there is no need for it.

**Pull request closed without merging**
